services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3006}
      PORT: "3006"
      HOSTNAME: 0.0.0.0
      RUN_DB_MIGRATIONS: ${RUN_DB_MIGRATIONS:-true}
    ports:
      - "3006:3006"
    restart: unless-stopped
    networks:
      - dokploy-network

  prisma_studio:
    profiles: ["tools"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      RUN_DB_MIGRATIONS: "false"
    command:
      [
        "node_modules/.bin/prisma",
        "studio",
        "--hostname",
        "0.0.0.0",
        "--port",
        "5555",
      ]
    ports:
      - "5555:5555"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
